import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProjectUpdates1788760000000 implements MigrationInterface {
  name = 'CreateProjectUpdates1788760000000';
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE project_updates (id int NOT NULL AUTO_INCREMENT, project_id int NOT NULL, organization_id varchar(36) NOT NULL, author_id bigint NOT NULL, health enum ('on_track','at_risk','off_track') NOT NULL, accomplishments longtext NULL, blockers longtext NULL, next_steps longtext NULL, reporting_period_start date NULL, reporting_period_end date NULL, status enum ('draft','published') NOT NULL DEFAULT 'draft', series_id int NULL, corrects_update_id int NULL, version int NOT NULL DEFAULT 1, published_at datetime NULL, created_at datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX IDX_project_updates_scope (organization_id, project_id, status, created_at), INDEX IDX_project_updates_series (series_id, version), UNIQUE INDEX UQ_project_updates_series_version (series_id, version), PRIMARY KEY (id), CONSTRAINT FK_project_updates_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE, CONSTRAINT FK_project_updates_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE, CONSTRAINT FK_project_updates_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT FK_project_updates_corrects FOREIGN KEY (corrects_update_id) REFERENCES project_updates(id) ON DELETE SET NULL) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE project_update_references (id int NOT NULL AUTO_INCREMENT, project_update_id int NOT NULL, reference_type enum ('task','milestone','document','user') NOT NULL, reference_id varchar(64) NOT NULL, snapshot_label varchar(255) NOT NULL, INDEX IDX_project_update_refs_update (project_update_id), UNIQUE INDEX UQ_project_update_ref (project_update_id, reference_type, reference_id), PRIMARY KEY (id), CONSTRAINT FK_project_update_refs_update FOREIGN KEY (project_update_id) REFERENCES project_updates(id) ON DELETE CASCADE) ENGINE=InnoDB`);
  }
  async down(queryRunner: QueryRunner): Promise<void> { await queryRunner.query('DROP TABLE project_update_references'); await queryRunner.query('DROP TABLE project_updates'); }
}
