import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateRequestForms1788950000000 implements MigrationInterface {
  name = 'CreateRequestForms1788950000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'CREATE TABLE `request_forms` (`id` varchar(36) NOT NULL, `organization_id` varchar(36) NOT NULL, `project_id` int NOT NULL, `public_key` varchar(64) NOT NULL, `name` varchar(180) NOT NULL, `created_by_id` bigint NOT NULL, `archived_at` datetime NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX `UQ_request_form_public_key` (`public_key`), INDEX `IDX_request_forms_project_archive` (`project_id`,`archived_at`), INDEX `IDX_request_forms_organization` (`organization_id`), PRIMARY KEY (`id`), CONSTRAINT `FK_request_forms_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_request_forms_project` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_request_forms_creator` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT) ENGINE=InnoDB',
    );
    await queryRunner.query(
      "CREATE TABLE `request_form_versions` (`id` varchar(36) NOT NULL, `form_id` varchar(36) NOT NULL, `version_number` int UNSIGNED NOT NULL, `state` enum ('draft','published','retired') NOT NULL, `title` varchar(180) NOT NULL, `description` text NULL, `visibility` enum ('public','organization') NOT NULL, `destination_status_id` int NOT NULL, `confirmation_text` text NULL, `created_by_id` bigint NULL, `published_by_id` bigint NULL, `published_at` datetime NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX `UQ_request_form_version_number` (`form_id`,`version_number`), INDEX `IDX_request_form_version_state` (`form_id`,`state`), PRIMARY KEY (`id`), CONSTRAINT `FK_request_form_versions_form` FOREIGN KEY (`form_id`) REFERENCES `request_forms`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_request_form_versions_status` FOREIGN KEY (`destination_status_id`) REFERENCES `status`(`id`) ON DELETE RESTRICT, CONSTRAINT `FK_request_form_versions_creator` FOREIGN KEY (`created_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL, CONSTRAINT `FK_request_form_versions_publisher` FOREIGN KEY (`published_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL) ENGINE=InnoDB",
    );
    await queryRunner.query(
      "CREATE TABLE `request_form_fields` (`id` varchar(36) NOT NULL, `version_id` varchar(36) NOT NULL, `key` varchar(80) NOT NULL, `label` varchar(180) NOT NULL, `description` text NULL, `input_type` enum ('text','textarea','number','date','single_select','multi_select','checkbox','person','url','email','file') NOT NULL, `target_type` enum ('standard','custom_field','submission_only') NOT NULL, `standard_field` varchar(64) NULL, `custom_field_id` varchar(36) NULL, `required` tinyint NOT NULL DEFAULT 0, `position` int UNSIGNED NOT NULL DEFAULT 0, `options_snapshot` json NULL, `conditions` json NULL, `config` json NULL, UNIQUE INDEX `UQ_request_form_field_key` (`version_id`,`key`), INDEX `IDX_request_form_field_order` (`version_id`,`position`), INDEX `IDX_request_form_field_custom` (`custom_field_id`), PRIMARY KEY (`id`), CONSTRAINT `FK_request_form_fields_version` FOREIGN KEY (`version_id`) REFERENCES `request_form_versions`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_request_form_fields_custom` FOREIGN KEY (`custom_field_id`) REFERENCES `custom_field_definitions`(`id`) ON DELETE RESTRICT) ENGINE=InnoDB",
    );
    await queryRunner.query(
      "CREATE TABLE `request_form_submissions` (`id` varchar(36) NOT NULL, `organization_id` varchar(36) NOT NULL, `project_id` int NOT NULL, `form_id` varchar(36) NOT NULL, `version_id` varchar(36) NOT NULL, `task_id` int NULL, `submitted_by_id` bigint NULL, `submitter_email` varchar(255) NULL, `status` enum ('received','accepted','rejected','quarantined','failed') NOT NULL, `answers_snapshot` json NOT NULL, `validation_snapshot` json NULL, `source_ip_hash` varchar(64) NULL, `user_agent` varchar(255) NULL, `failure_reason` text NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX `IDX_request_form_submission_form_created` (`form_id`,`created_at`), INDEX `IDX_request_form_submission_project_created` (`project_id`,`created_at`), INDEX `IDX_request_form_submission_version` (`version_id`), INDEX `IDX_request_form_submission_org` (`organization_id`), PRIMARY KEY (`id`), CONSTRAINT `FK_request_form_submissions_organization` FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_request_form_submissions_project` FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON DELETE CASCADE, CONSTRAINT `FK_request_form_submissions_form` FOREIGN KEY (`form_id`) REFERENCES `request_forms`(`id`) ON DELETE RESTRICT, CONSTRAINT `FK_request_form_submissions_version` FOREIGN KEY (`version_id`) REFERENCES `request_form_versions`(`id`) ON DELETE RESTRICT, CONSTRAINT `FK_request_form_submissions_task` FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE SET NULL, CONSTRAINT `FK_request_form_submissions_submitter` FOREIGN KEY (`submitted_by_id`) REFERENCES `users`(`id`) ON DELETE SET NULL) ENGINE=InnoDB",
    );
    await queryRunner.query(
      "CREATE TABLE `request_form_submission_attachments` (`id` varchar(36) NOT NULL, `submission_id` varchar(36) NOT NULL, `original_name` varchar(255) NOT NULL, `storage_key` varchar(255) NOT NULL, `mime_type` varchar(180) NOT NULL, `size_bytes` bigint UNSIGNED NOT NULL, `sha256` varchar(64) NULL, `status` enum ('pending','accepted','quarantined','rejected') NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX `IDX_request_form_attachment_submission` (`submission_id`), PRIMARY KEY (`id`), CONSTRAINT `FK_request_form_attachments_submission` FOREIGN KEY (`submission_id`) REFERENCES `request_form_submissions`(`id`) ON DELETE CASCADE) ENGINE=InnoDB",
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE `request_form_submission_attachments`');
    await queryRunner.query('DROP TABLE `request_form_submissions`');
    await queryRunner.query('DROP TABLE `request_form_fields`');
    await queryRunner.query('DROP TABLE `request_form_versions`');
    await queryRunner.query('DROP TABLE `request_forms`');
  }
}
